### ISSUE TITLE
stage1 pretraining

### ISSUE THREAD

**Issue by mactavish91** [thuanz123/enhancing-transformers#14]
Thank you for your great work! I want to train a stage1 version myself. If I raise the dataset of stage1 to the billion level, will it improve the reconstruction quality?

**Comment by thuanz123** [comment]
Hi @mactavish91, big data is where ViT shines best and I would think it is the same for ViT-VQGAN.

**Comment by mactavish91** [comment]
@thuanz123 hello, I want to speed up training by using mixed precision training, but I found that some custom operators are not supported, such as fused_bias_act and upfirdn2d. When running, it produces an error: 
···RuntimeError: expected scalar type Half but found Float.··· Is there any way to solve this problem?

**Comment by PanXiebit** [comment]
same issue

> @thuanz123 hello, I want to speed up training by using mixed precision training, but I found that some custom operators are not supported, such as fused_bias_act and upfirdn2d. When running, it produces an error: `RuntimeError: expected scalar type Half but found Float` Is there any way to solve this problem?

same issue

**Comment by thuanz123** [comment]
Hi @mactavish91, can you specify what you did to use mixed precision training and can you post the full error log here so that I can fully understand what happened

**Comment by thuanz123** [comment]
Ah I see what is wrong, the custom operators at [here](https://github.com/thuanz123/enhancing-transformers/tree/main/enhancing/losses/op) do not have amp autocast. There are two ways to fix this issue:

1. You can try this new [branch](https://github.com/thuanz123/enhancing-transformers/tree/amp-fixed) that I just create. Although it is runable, this branch haven't been carefully tested yet so the performance may be not as good as the main branch.
2. You can switch to use [PatchDisciminator](https://github.com/thuanz123/enhancing-transformers/blob/amp-fixed/enhancing/losses/layers.py#L267) instead of [StyleDiscriminator](https://github.com/thuanz123/enhancing-transformers/blob/amp-fixed/enhancing/losses/layers.py#L322)

**Comment by mactavish91** [comment]
> Ah I see what is wrong, the custom operators at [here](https://github.com/thuanz123/enhancing-transformers/tree/main/enhancing/losses/op) do not have amp autocast. There are two ways to fix this issue:
> 
> 1. You can try this new [branch](https://github.com/thuanz123/enhancing-transformers/tree/amp-fixed) that I just create. Although it is runable, this branch haven't been carefully tested yet so the performance may be not as good as the main branch.
> 2. You can switch to use [PatchDisciminator](https://github.com/thuanz123/enhancing-transformers/blob/amp-fixed/enhancing/losses/layers.py#L267) instead of [StyleDiscriminator](https://github.com/thuanz123/enhancing-transformers/blob/amp-fixed/enhancing/losses/layers.py#L322)

@thuanz123 Thank you for your kind assistance. Could you please provide your wandb training records? I noticed that my GAN loss has been consistently at a very high value, which is affecting the training process.
![QQ截图20230522152948](https://github.com/thuanz123/enhancing-transformers/assets/58135925/adc9d3fc-4d8a-477a-8e07-083fc39df477)

**Comment by thuanz123** [comment]
Yes, this loss log is normal. GAN loss is not as indicative as other losses. You only need to look at reconstruction loss see if it decreases or not and check the visual quality of the reconstructed images
